#!/bin/sh

DIR="$HOME/.cache/snooze"
SCRIPTS_DIR="$HOME/.local/bin/snooze/daily"
mkdir -p "$DIR"
sleep 5m
exec snooze -s 1d -R 10m -t "$DIR/daily" -- sh -c \
	"test -d $SCRIPTS_DIR/daily && run-parts --lsbsysinit $SCRIPTS_DIR/daily; : > $DIR/daily"
