#!/bin/sh

export BROWSER="uchromium"
export GDK_DPI_SCALE=1.5

mpd &
remaps &		# run the remaps script, switching caps/esc and more; check it for more info
# setbg &			# set the background with the `setbg` script
# picom &
# xcompmgr &		# xcompmgr for transparency
dunst &			# dunst for notifications
xset r rate 300 50 &	# Speed xrate up
unclutter &		# Remove mouse when idle
xrdb ${XDG_CONFIG_HOME:-$HOME/.config}/Xresources &	# Uncomment to use Xresources colors/settings on startup
numlockx &
syncthing -no-browser &
sudo runsv /var/service/chronyd &
sudo runsv /var/service/socklog-unix &
sudo runsv /var/service/nanoklogd &
sudo runsv /var/service/sshd &
sudo runsv /var/service/dcron &

sh ~/.config/screenlayout/Desktop/main.sh
timeOnPc start
# sudo tlp bat

blacklist on
notify-send -i "${XDG_PICTURES_DIR:-$HOME/Storage/Pictures}/Art/Redge-hp.jpg" "<Welcome>" "Today is a great day to suck"
echo "\a" > /dev/tty5	# beep
# echo -en "\a" > /dev/tty5	# beep
