#!/bin/bash

set -C -f
IFS="$(printf '%b_' '\n')"; IFS="${IFS%_}"

preview() {
	cat <<-EOF | paste -sd '' >"$LF_UEBERZUG_TEMPDIR/fifo"
		{
		"action": "add", "identifier": "lf-preview",
		"path": "$1", "x": $4, "y": $5, "width": $2, "height": $3,
		"scaler": "contain"
		}
	EOF
}

~/.config/lf/cleaner
FILE_PATH="${1}"
shift
case "$(basename "$FILE_PATH" | tr '[:upper:]' '[:lower:]')" in
	*.tar*) tar tf "$FILE_PATH" ;;
	*.zip) unzip -l "$FILE_PATH" ;;
	*.rar) unrar l "$FILE_PATH" ;;
	*.7z) 7z l "$FILE_PATH" ;;
	*.torrent) transmission-show "$1" ;;
	*.o) nm "$1" | less ;;
	*.docx | *.odt | *.epub) pandoc -s -t plain -- "$FILE_PATH" | head -n 100 ;;
	*.djvu | *.djv)
		thumbnail="$LF_UEBERZUG_TEMPDIR/thumbnail.png"
		ddjvu -format=pdf -quality=90 -page=1 "$FILE_PATH" "$thumbnail.pdf"
		gs -o "$thumbnail" -sDEVICE=pngalpha -dLastPage=1 "$thumbnail.pdf" >/dev/null
		preview "$thumbnail" "$@"
		;;
	*.pdf)
		thumbnail="$LF_UEBERZUG_TEMPDIR/thumbnail.png"
		gs -o "$thumbnail" -sDEVICE=pngalpha -dLastPage=1 "$FILE_PATH" >/dev/null
		preview "$thumbnail" "$@"
		;;
	*.svg)
		thumbnail="$LF_UEBERZUG_TEMPDIR/thumbnail.png"
		gm convert "$FILE_PATH" "$thumbnail"
		preview "$thumbnail" "$@"
		;;
	*.gif)
		thumbnail="$LF_UEBERZUG_TEMPDIR/thumbnail.png"
		gm convert "${FILE_PATH[0]}" "$thumbnail"
		preview "$thumbnail" "$@"
		;;
esac

# case "$(FILE_PATH -Lb --mime-type -- "$file")" in
case "$(file --dereference --brief --mime-type -- "${FILE_PATH}")" in
	audio/* | application/octet-stream) mediainfo "$FILE_PATH" ;;
	application/pgp-encrypted) gpg -d -- "${FILE_PATH}" ;;
	application/zip) atool --list -- "${FILE_PATH}" ;;
	*opendocument*) odt2txt "${FILE_PATH}" ;;
	image/*) preview "$FILE_PATH" "$@" ;;
	text/html) lynx -display_charset=utf-8 -dump "${FILE_PATH_PATH}" | head -n 50 ;;
 	text/* | */xml | application/json) bat --terminal-width "$4" -f "$1" ;;
	text/troff) man ./ "${FILE_PATH}" | col -b ;;
	video/*) mediainfo "$FILE_PATH" ;;
		# thumbnail="$LF_UEBERZUG_TEMPDIR/thumbnail.png"
		# ffmpeg -y -i "$FILE_PATH" -vframes 1 "$thumbnail"
		# preview "$thumbnail" "$@"
		# ;;
esac

return 127 # nonzero retcode required for lf previews to reload
