#!/bin/sh

export USER="$(cat /etc/passwd | grep 1000 | cut -d':' -f1)"
export HOME="/home/$USER"

groups="$(id -Gn "$USER" | tr ' ' ':')"
svdir="$HOME/.local/service"

exec chpst -u "$USER:$groups" runsvdir "$svdir"
