#!/bin/sh

export EDITOR="nvim"
export FILE="lf"
export READER="zathura"
export TERMINAL="st"

export PATH="$PATH:$(du "$HOME/.local/bin/" | cut -f2 | paste -sd ':' -)"
# export PATH="$PATH:${$(find ~/.local/bin -type d -printf %p:)%%:}"

export XDG_CACHE_HOME="$HOME/.cache"
export XDG_CONFIG_HOME="$HOME/.config"
export XDG_DATA_HOME="$HOME/.local/share"
export XDG_DOCUMENTS_DIR="$HOME/Documents"
export XDG_DOWNLOAD_DIR="$HOME/Downloads"
export XDG_MUSIC_DIR="$HOME/Storage/Music"
export XDG_PICTURES_DIR="$HOME/Storage/Pictures"
export XDG_RUNTIME_DIR="$HOME/.cache"
export XDG_VIDEOS_DIR="$HOME/Storage/Videos"

export _JAVA_OPTIONS="-Djava.util.prefs.userRoot=\"$XDG_CONFIG_HOME\"/java"
#export ALSA_CONFIG_PATH="$XDG_CONFIG_HOME/alsa/asoundrc"
export AWT_TOOLKIT="MToolkit wmname LG3D"	#May have to install wmname
export CUDA_CACHE_PATH="$XDG_CONFIG_HOME/nv"
# export GDK_SCALE=1.5
# export GDK_DPI_SCALE=1.5
export GNUPGHOME="$XDG_CONFIG_HOME/gnupg"
export GTK2_RC_FILES="$XDG_CONFIG_HOME/gtk-2.0/gtkrc-2.0"
export INPUTRC="$XDG_CONFIG_HOME/shell/inputrc"
export LESSHISTFILE="-"
export MESA_LOADER_DRIVER_OVERRIDE="i965"
export MOZ_USE_XINPUT2="1"		# Mozilla smooth scrolling/touchpads.
export OCTAVE_HISTFILE="$XDG_CACHE_HOME/octave-hsts"
export OCTAVE_SITE_INITFILE="$XDG_CONFIG_HOME/octave/octaverc"
export PASSWORD_STORE_DIR="$HOME/.local/share/password-store"
export QT_QPA_PLATFORMTHEME="gtk3"	# Have QT use gtk2 theme.
export QT_STYLE_OVERRIDE="gtk3"
# export QT_SCALE_FACTOR=1.5
export SUDO_ASKPASS="$HOME/.local/bin/tools/dmenupass"
export TASKDATA="$XDG_DATA_HOME/task"
export TASKRC="$XDG_CONFIG_HOME/task/taskrc"
# export TERM="screen-256color"
export TERMINFO="$XDG_DATA_HOME/terminfo"
export TERMINFO_DIRS="$XDG_DATA_HOME/terminfo:/usr/share/terminfo"
export TEXMFHOME="$XDG_DATA_HOME/texmf"
export TEXMFVAR="$XDG_CACHE_HOME/texlive/texmf-var"
export TEXMFCONFIG="$XDG_CONFIG_HOME/texlive/texmf-config"
export TIMEWARRIORDB="$XDG_CONFIG_HOME/timewarrior"
export TMUX_TMPDIR="$XDG_RUNTIME_DIR"
export WGETRC="$XDG_CONFIG_HOME/wget/wgetrc"
export XAUTHORITY="$XDG_CONFIG_HOME/Xauthority"
export ZDOTDIR="$XDG_CONFIG_HOME/zsh"
export _JAVA_AWT_WM_NONREPARENTING=1	# Java doesn't understand tiling windows

# less/man colors
#export DICS="/usr/share/stardict/dic/"
export SUDO_ASKPASS="$HOME/.local/bin/dmenupass"
export FZF_DEFAULT_OPTS="--layout=reverse --height 40%"
export LESS=-R
export LESS_TERMCAP_mb="$(printf '%b' '[1;31m')"
export LESS_TERMCAP_md="$(printf '%b' '[1;36m')"
export LESS_TERMCAP_me="$(printf '%b' '[0m')"
export LESS_TERMCAP_so="$(printf '%b' '[01;44;33m')"
export LESS_TERMCAP_se="$(printf '%b' '[0m')"
export LESS_TERMCAP_us="$(printf '%b' '[1;32m')"
export LESS_TERMCAP_ue="$(printf '%b' '[0m')"

[ ! -f ${XDG_CONFIG_HOME:-$HOME/.config}/shell/shortcutrc ] && shortcuts >/dev/null 2>&1 &
# echo "$0" | grep "bash$" >/dev/null && [ -f ~/.bashrc ] && source "$HOME/.bashrc"

export LF_ICONS="di=📁:\
fi=📃:\
tw=🤝:\
ow=📂:\
ln=:\
or=❌:\
ex=:\
*.1=ℹ:\
*.7z=📦:\
*.bib=🎓:\
*.c=:\
*.cc=:\
*.clj=:\
*.coffee=:\
*.cpp=:\
*.css=:\
*.css=🎨:\
*.csv=📓:\
*.d=:\
*.dart=:\
*.djvu=📚:\
*.epub=📚:\
*.erl=:\
*.exs=:\
*.flac=🎵:\
*.fs=:\
*.ged=👪:\
*.gif=:\
*.go=:\
*.gpg=🔒:\
*.h=:\
*.hh=:\
*.hpp=:\
*.hs=:\
*.html=:\
*.ico=:\
*.img=📀:\
*.info=ℹ:\
*.iso=📀:\
*.java=:\
*.jl=:\
*.jpeg=:\
*.jpg=:\
*.js=:\
*.json=:\
*.log=📙:\
*.lua=:\
*.m4a=🎵:\
*.md=:\
*.md=📘:\
*.me=✍:\
*.mkv=🎥:\
*.mom=✍:\
*.mp3=🎵:\
*.mp4=🎥:\
*.mpeg=🎥:\
*.ms=✍:\
*.n64=🎮:\
*.nfo=ℹ:\
*.ogg=🎵:\
*.opus=🎵:\
*.part=💔:\
*.pdf=📚:\
*.php=:\
*.pl=:\
*.png=:\
*.pro=:\
*.py=:\
*.R=📊:\
*.r=📊:\
*.rar=📦:\
*.rb=:\
*.Rmd=📊:\
*.rmd=📊:\
*.rs=:\
*.scala=:\
*.svg=🗺:\
*.tar.gz=📦:\
*.tex=📜:\
*.torrent=🔽:\
*.ts=:\
*.txt=✍:\
*.v64=🎮:\
*.vim=
*.webm=🎥:\
*.xcf=🖌:\
*.xlsx=📓:\
*.xml=📰:\
*.z64=🎮:\
*.zip=📦:\
"
# Start graphical server on user's current tty if not already running.
	[[ -n "$(tty)" && -z $(pgrep -u $USER "\bXorg$") ]] && exec startx

# Switch escape and caps if tty:
sudo -n loadkeys ~/.local/bin/ttymaps.kmap 2>/dev/null
