widget_defaults = dict(
    font="DaddyTimeMono Nerd Font Bold",
    # font="VictorMono Nerd Font Bold",
    fontsize=13,
    padding=4,
    background=colors[0],
)
extension_defaults = widget_defaults.copy()

screens = [
    Screen(
        wallpaper="~/.local/share/bg",
        wallpaper_mode="stretch",
        top=bar.Bar(
            [
                widget.GroupBox(
                    padding=4,
                    active=colors[2],
                    inactive=colors[1],
                    highlight_color=[backgroundColor, workspaceColor],
                    this_screen_border=colors[2],
                    this_current_screen_border=colors[2],
                    other_screen_border=colors[2],
                    other_current_screen_border=colors[2],
                    highlight_method="line",
                    hide_unused=True,
                ),
                widget.TextBox(
                    text="\u25e2",
                    padding=0,
                    fontsize=50,
                    background=backgroundColor,
                    foreground=workspaceColor,
                ),
                widget.CurrentLayout(
                    background=workspaceColor,
                ),
                widget.TextBox(
                    text="\u25e2",
                    padding=0,
                    fontsize=50,
                    background=workspaceColor,
                    foreground=backgroundColor,
                ),
                widget.Spacer(
                    length=20,
                ),
                widget.WindowCount(foreground=colors[7]),
                widget.WindowName(
                    foreground=colors[8],
                ),
                # widget.WindowTabs(
                #     selected=('<u>« ',' »</u>'),
                #     separator='      ',
                #     foreground=colors[8],
                #     # background=colors[2],
                # ),
                widget.TextBox(
                    text="\u25e2",
                    padding=0,
                    fontsize=50,
                    background=backgroundColor,
                    foreground=foregroundColorTwo,
                ),
                widget.TextBox(
                    text="\u25e2",
                    padding=0,
                    fontsize=50,
                    background=foregroundColorTwo,
                    foreground=foregroundColorTwo,
                ),
                widget.Prompt(
                    bell_style="visual",
                    cursorblink=0.5,
                    fontsize=18,
                    prompt="&:",
                    foreground=colors[9],
                    background=foregroundColorTwo,
                ),
                # widget.GenPollText( # sb-music
                #     update_interval=10,
                #     func=lambda: subprocess.check_output(os.path.expanduser("~/.local/bin/statusbar/sb-music")),
                # ),
                # widget.Mpd2(
                #     status_format='{play_status} [{artist:.15s}]-[{album:.15s}]-[{title:.30s}]',
                #     idle_message="mpd",
                #     color_progress="#9497aa",
                #     update_interval=10,
                #     foreground=colors[9],
                #     background=foregroundColorTwo,
                # ),
                widget.CPU(
                    format="{load_percent:-2.1f}% {freq_current}GHz",
                    update_interval=3,
                    foreground=colors[5],
                    background=foregroundColorTwo,
                ),
                widget.Load(
                    update_interval=3,
                    format="{time}:{load:.2f}",
                    foreground=colors[4],
                    background=foregroundColorTwo,
                ),
                widget.ThermalSensor(
                    update_interval=30,
                    format=" {temp:.0f}{unit}",
                    tag_sensor="Package id 0",
                    foreground=colors[6],
                    background=foregroundColorTwo,
                ),
                widget.NvidiaSensors(
                    update_interval=30,
                    # format=' {temp:.0f}{unit}',
                    gpu_bus_id="01:00.0",
                    tag_sensor="Package id 0",
                    foreground=colors[6],
                    background=foregroundColorTwo,
                ),
                widget.Memory(
                    update_interval=15,
                    format=" {MemUsed:.0f}{ms}/{SwapUsed:.0f}{ms}",
                    foreground=colors[7],
                    background=foregroundColorTwo,
                ),
                # widget.Wlan(
                #     disconnected_message='❌',
                #     format='{essid} {percent:2.0%}',
                #     update_interval=10,
                #     foreground=colors[4],
                #     background=foregroundColorTwo,
                # ),
                widget.Volume(
                    fmt=" {}",
                    update_interval=1,
                    step=5,
                    foreground=colors[8],
                    background=foregroundColorTwo,
                    # fmt=" {}"
                ),
                # widget.Net(
                #     fmt=' {}',
                #     update_interval=2,
                #     foreground=colors[9],
                #     background=foregroundColorTwo,
                # ),
                # widget.Backlight(
                #     update_interval = 15,
                #     foreground=colors[8],
                #     background=foregroundColorTwo,
                #     ),
                # widget.Battery(
                #     update_interval=15,
                #     format='{char} {percent:2.0%} {hour:d}:{min:02d} {watt:.2f} W',
                #     low_precentage=0.35,
                #     charge_char='',
                #     discharge_char='',
                #     empty_char='',
                #     foreground=colors[6],
                #     background=foregroundColorTwo,
                #      ),
                widget.TextBox(
                    text="\u25e2",
                    padding=0,
                    fontsize=50,
                    background=foregroundColorTwo,
                    foreground=workspaceColor,
                ),
                widget.Systray(background=workspaceColor, foreground=backgroundColor),
                widget.TextBox(
                    text="\u25e2",
                    padding=0,
                    fontsize=50,
                    background=workspaceColor,
                    foreground=backgroundColor,
                ),
                widget.Clock(
                    format=" %V %a %d/%B/%y",
                    update_interval=86400,
                    foreground=colors[10],
                    background=backgroundColor,
                ),
                widget.Clock(
                    format=" %T",
                    update_interval=1,
                    foreground=colors[2],
                    background=backgroundColor,
                ),
                widget.Pomodoro(
                    update_interval=1,
                    prefix_active=" ",
                    prefix_break="🛑",
                    prefix_long_break="🛑🛑",
                    prefix_inactive="🔃",
                    # prefix_paused=️'',
                    foreground=colors[1],
                    background=backgroundColor,
                    color_active=colors[4],
                    color_inactive=colors[6],
                ),
            ],
            20,
        ),
    ),
    Screen(
        wallpaper="~/.local/share/bg",
        wallpaper_mode="stretch",
        top=bar.Bar(
            [
                widget.GroupBox(
                    padding=4,
                    active=colors[2],
                    inactive=colors[1],
                    highlight_color=[backgroundColor, workspaceColor],
                    this_screen_border=colors[2],
                    this_current_screen_border=colors[2],
                    other_screen_border=colors[2],
                    other_current_screen_border=colors[2],
                    highlight_method="line",
                    hide_unused=True,
                ),
                widget.TextBox(
                    text="\u25e2",
                    padding=0,
                    fontsize=50,
                    background=backgroundColor,
                    foreground=workspaceColor,
                ),
                widget.CurrentLayout(
                    scale=0.7,
                    background=workspaceColor,
                ),
                widget.TextBox(
                    text="\u25e2",
                    padding=0,
                    fontsize=50,
                    background=workspaceColor,
                    foreground=backgroundColor,
                ),
                widget.WindowCount(foreground=colors[7]),
                widget.WindowName(
                    foreground=colors[8],
                ),
                # widget.WindowTabs(
                #     selected=('<u>« ',' »</u>'),
                #     separator='      ',
                #     foreground=colors[8],
                #     # background=colors[2],
                # ),
                widget.TextBox(
                    text="\u25e2",
                    padding=0,
                    fontsize=50,
                    background=backgroundColor,
                    foreground=foregroundColorTwo,
                ),
                # widget.Mpd2(
                #     status_format='{play_status} [{artist:.15s}]-[{album:.15s}]-[{title:.30s}]',
                #     idle_message="mpd",
                #     color_progress="#9497aa",
                #     update_interval=10,
                #     foreground=colors[9],
                #     background=foregroundColorTwo,
                # ),
                # widget.Net(
                #     fmt=' {}',
                #     update_interval=2,
                #     foreground=colors[9],
                #     background=foregroundColorTwo,
                # ),
                widget.TextBox(
                    text="\u25e2",
                    padding=0,
                    fontsize=14,
                    background=foregroundColorTwo,
                    foreground=foregroundColorTwo,
                ),
                widget.Prompt(
                    bell_style="visual",
                    cursorblink=0.5,
                    fontsize=18,
                    prompt="&:",
                    foreground=colors[9],
                    background=foregroundColorTwo,
                ),
                # widget.Countdown(
                #     # format='{D}d {H}h {M}m {S}s',
                #     date=datetime(2023, 10, 5, 0, 0, 0, 0),
                #     foreground=colors[3],
                #     background=foregroundColorTwo,
                #     color_active=colors[4],
                #     color_inactive=foregroundColorTwo
                # ),
                # widget.Backlight(
                #     update_interval = 15,
                #     foreground=colors[8],
                #     background=foregroundColorTwo,
                #     ),
                # widget.Battery(
                #     update_interval=15,
                #     format='{char} {percent:2.0%} {hour:d}:{min:02d} {watt:.2f} W',
                #     low_precentage=0.35,
                #     charge_char='',
                #     discharge_char='',
                #     empty_char='',
                #     foreground=colors[6],
                #     background=foregroundColorTwo,
                #      ),
                # widget.HDDBusyGraph(
                #     frequency=5,
                #     start_pos='top',
                #     graph_color=colors[8],
                #     background=foregroundColorTwo,
                # ),
                widget.TextBox(
                    text="\u25e2",
                    padding=0,
                    fontsize=50,
                    background=foregroundColorTwo,
                    foreground=backgroundColor,
                ),
                widget.Clipboard(
                    # update_interval=1,
                    foreground=colors[3],
                    background=backgroundColor,
                    color_active=colors[4],
                    color_inactive=foregroundColorTwo,
                ),
            ],
            20,
        ),
    ),
]
# }}}
