#!/bin/sh

export BROWSER="librewolf"
export BROWSER2="qutebrowser"
# export GDK_DPI_SCALE=1.5
# export QT_SCALE_FACTOR=1.5
# export QT_ENABLE_HIGHDPI_SCALING=1

sh ~/.config/screenlayout/Desktop/hdmi:4k.sh &
doas intel-undervolt apply &
[ ! -s ~/.config/mpd/pid ] && mpd  &
remaps &
# xcompmgr &
dunst &
unclutter &
numlockx &
redshift -l 43.50:13.01 -t 5700:3600 -g 0.8 -m randr &
clipmenud &
# caffeine &
timeOnPc start &
xautolock -time 15 -notify 180 -notifier "notify-send -u critical -t 180000 'System will be locked' '3 minute left'" -locker 'doas zzz' &
blacklist on &
notify-send -i "${XDG_PICTURES_DIR:-$HOME/Storage/Pictures}/UserImg.jpg" "«Welcome»" "$(date)"
echo "\a" >/dev/tty5 # beep
emacs --daemon &
# QSyncthingTray &
doas tlp start
