#!/bin/sh

export BROWSER="librewolf"
# export GDK_DPI_SCALE=1.5

mpd &
remaps &		# run the remaps script, switching caps/esc and more; check it for more info
setbg &			# set the background with the `setbg` script
# xcompmgr &		# xcompmgr for transparency
dunst &			# dunst for notifications
xset r rate 300 50 &	# Speed xrate up
unclutter &		# Remove mouse when idle
xrdb ${XDG_CONFIG_HOME:-$HOME/.config}/X11/xresources &	# Uncomment to use Xresources colors/settings on startup
numlockx &
syncthing -no-browser &
redshift -l 43.5942:13.5034 &
doas runsv /var/service/chronyd &
doas runsv /var/service/socklog-unix &
doas runsv /var/service/nanoklogd &
doas runsv /var/service/sshd &
doas runsv /var/service/NetworkManager &
doas intel-undervolt apply
# sudo runsv /var/service/dcron &

sh ~/.config/screenlayout/Desktop/second.sh
timeOnPc start
# sudo tlp bat

xautolock -time 20 -notify 180 -notifier "notify-send -u critical -t 60000 'System will be locked' '1 minute left'" -locker 'doas zzz' &
blacklist on
notify-send -i "$(${XDG_PICTURES_DIR:-$HOME/Storage/Pictures}/UserImg.jpg)" "<Welcome>" "Today is a great day to suck"
# echo "\a" > /dev/tty5	# beep
