#!/bin/sh

export BROWSER="librewolf"
export BROWSER2="qutebrowser"
# export GDK_DPI_SCALE=1.5
# export QT_SCALE_FACTOR=1.5
# export QT_ENABLE_HIGHDPI_SCALING=1

doas runsv /var/service/chronyd &
doas runsv /var/service/socklog-unix &
doas runsv /var/service/nanoklogd &
# doas runsv /var/service/sshd &
doas runsv /var/service/NetworkManager &
# sudo runsv /var/service/dcron &
doas intel-undervolt apply &

mpd &
remaps &
# xcompmgr &
dunst &
unclutter &
numlockx &
# QsyncthingTray &
redshift -l 43.59:12.50 -t 5700:3600 -g 0.8 -m randr &
clipmenud &
caffeine &

sh ~/.config/screenlayout/Desktop/hdmi:4k.sh &
timeOnPc start &
xautolock -time 15 -notify 180 -notifier "notify-send -u critical -t 180000 'System will be locked' '3 minute left'" -locker 'doas zzz' &
blacklist on &
notify-send -i "${XDG_PICTURES_DIR:-$HOME/Storage/Pictures}/UserImg.jpg" "«Welcome»" "$(date)"
echo "\a" > /dev/tty5	# beep
