#!/bin/sh

export BROWSER="qutebrowser"

mpd &
remaps &
setbg &
dunst &
unclutter &
# xrdb ${XDG_CONFIG_HOME:-$HOME/.config}/x11/xresources &
xautolock -time 5 -notify 60 -notifier notifylock -locker lock &
# QsyncthingTray -no-browser &
clipmenud &
numlockx &
doas intel-undervolt apply &
redshift -l 43.5943:12.5034 -t 5700:3600 -g 0.8 -m randr &
nm-applet &
blueman-applet &
bluetooth off &
# caffeine &
blacklist on &
xbacklight -set 20 &
libinput-gestures-setup start &
timeOnPc start &
notify-send -i "${XDG_PICTURES_DIR:-$HOME/Storage/Pictures}/UserImg.jpg" "«Welcome»"
# aw-qt &
emacs --daemon &
