#!/bin/sh

export BROWSER="qutebrowser"

setbg &
dunst &
unclutter &
[ ! -s ~/.config/mpd/pid ] && mpd  &
remaps &
clipmenud &
timeOnPc start
libinput-gestures-setup start
redshift -l 43.5943:12.5034 -t 5700:3600 -g 0.8 -m randr &
xautolock -time 15 -notify 180 -notifier "notify-send -u critical -t 180000 'System will be locked' '3 minute left'" -locker 'doas zzz' &
blacklist on &
notify-send -i "${XDG_PICTURES_DIR:-$HOME/Storage/Pictures}/UserImg.jpg" "«Welcome»" "$(date)"
emacs --daemon &
syncthing &
