#!/bin/sh

export BROWSER="qutebrowser"

mpd &
remaps &		# run the remaps script, switching caps/esc and more; check it for more info
setbg &			# set the background with the `setbg` script
dunst &			# dunst for notifications
unclutter &		# Remove mouse when idle

timeOnPc start
libinput-gestures-setup start
# sudo rfkill block wlan
# sudo tlp bat
blacklist on
notify-send -i /home/davide/.config/Icons/UserImg.png "<Welcome>" "Today is a great day to suck...less"
emacs --daemon &
syncthing &
