#!/bin/sh

export BROWSER="qutebrowser"
export EDITOR="nvim"
export FILE="lf"
export PAGER="bat"
export READER="zathura"
export TERMINAL="alacritty"
export VISUAL="em"
export ALTERNATE_BROWSER="librewolf"
export ALTERNATE_BROWSER_PRIVATE="librewolf --private-window"

export XDG_CACHE_HOME="$HOME/.cache"
export XDG_CONFIG_HOME="$HOME/.config"
export XDG_DATA_HOME="$HOME/.local/share"
export XDG_DOCUMENTS_DIR="$HOME/Documents"
export XDG_DOWNLOAD_DIR="$HOME/Downloads"
export XDG_MUSIC_DIR="$HOME/Storage/Music"
export XDG_PICTURES_DIR="$HOME/Storage/Pictures"
XDG_RUNTIME_DIR="/run/user/$(id -u)"
export XDG_RUNTIME_DIR
export XDG_VIDEOS_DIR="$HOME/Storage/Videos"

# export _JAVA_OPTIONS="-Djava.util.prefs.userRoot=\"$XDG_CONFIG_HOME\"/java"
# export ALSA_CONFIG_PATH="$XDG_CONFIG_HOME/alsa/asoundrc"
export AWT_TOOLKIT="MToolkit wmname LG3D" #May have to install wmname
export CALIBRE_USE_DARK_PALETTE=1
export CALIBRE_USE_SYSTEM_THEME=1
export CARGO_HOME="$XDG_DATA_HOME/cargo"
export CM_HISTLENGTH="12"
export CUDA_CACHE_PATH="$XDG_CONFIG_HOME/nv"
# export DIGESTIF_HOME="$XDG_DATA_HOME/digestif"
# export ELECTRUMDIR="${XDG_DATA_HOME:-$HOME/.local/share}/electrum"
# export GDK_DPI_SCALE=1.5
export GNUPGHOME="$XDG_CONFIG_HOME/gnupg"
export GOPATH="$XDG_DATA_HOME"/go
export GTK2_RC_FILES="$XDG_CONFIG_HOME/gtk-2.0/gtkrc-2.0"
export INPUTRC="$XDG_CONFIG_HOME/shell/inputrc"
export LESSHISTFILE="-"
# export MBSYNCRC="${XDG_CONFIG_HOME:-$HOME/.config}/mbsync/config"
# export MESA_LOADER_DRIVER_OVERRIDE="i965"
export MOZ_USE_XINPUT2="1" # Mozilla smooth scrolling/touchpads.
export NPM_CONFIG_USERCONFIG="$XDG_CONFIG_HOME/npm/npmrc"
export OCTAVE_HISTFILE="$XDG_CACHE_HOME/octave-hsts"
export OCTAVE_SITE_INITFILE="$XDG_CONFIG_HOME/octave/octaverc"
export PASSWORD_STORE_DIR="$HOME/.local/share/password-store"
export PYTHONUSERBASE="$HOME/.local/share/python"
# export QT_QPA_PLATFORMTHEME="gtk2"	# Have QT use gtk2 theme.
export QT_QPA_PLATFORMTHEME="qt5ct"
# export QT_STYLE_OVERRIDE="gtk3"
# export QT_SCALE_FACTOR=1.5
export RUSTUP_HOME="$XDG_DATA_HOME/rustup"
export SUDO_ASKPASS="$HOME/.local/bin/dmenu/dmenupass"
# export TASKDATA="$XDG_DATA_HOME/task"
# export TASKRC="$XDG_CONFIG_HOME/task/taskrc"
# export TERM="screen-256color"
export TERMINFO="$XDG_DATA_HOME/terminfo"
export TERMINFO_DIRS="$XDG_DATA_HOME/terminfo:/usr/share/terminfo"
export TEXMFHOME="$XDG_DATA_HOME/texmf"
export TEXMFVAR="$XDG_CACHE_HOME/texlive/texmf-var"
export TEXMFCONFIG="$XDG_CONFIG_HOME/texlive/texmf-config"
# export TIMEWARRIORDB="$XDG_CONFIG_HOME/timewarrior"
export TMUX_TMPDIR="$XDG_RUNTIME_DIR"
export WGETRC="$XDG_CONFIG_HOME/wget/wgetrc"
export XINITRC="${XDG_CONFIG_HOME:-$HOME/.config}/x11/xinitrc"
export XAUTHORITY="$XDG_CONFIG_HOME/Xauthority"
export ZDOTDIR="$XDG_CONFIG_HOME/zsh"
export _JAVA_AWT_WM_NONREPARENTING=1 # Java doesn't understand tiling windows

PATH="$PATH:$(du "$HOME/.local/bin/" | cut -f2 | paste -sd ':' -)"
PATH="$PATH:$HOME/.config/emacs/bin/"
PATH="$PATH:$HOME/.local/share/cargo/bin/"
PATH="$PATH:$HOME/.local/share/go/bin/"
PATH="$PATH:$HOME/.local/share/npm/bin/"
PATH="$PATH:$HOME/.local/share/python/bin/"
export PATH

export FZF_DEFAULT_OPTS="--layout=reverse \
--info=inline \
--height=100% \
--multi \
--preview-window=:hidden \
--preview 'bat --paging=never --line-range :80 {}' \
--prompt='» ' \
--pointer='▶' \
--marker='✓' \
--bind '?:toggle-preview' \
--bind 'ctrl-space:print-query' \
--bind 'ctrl-a:select-all' \
--bind 'ctrl-y:execute-silent(echo {+} | xclip -selection clipboard -i)' \
--bind 'ctrl-r:replace-query' \
--bind 'ctrl-e:execute(vim {+})'
--bind 'ctrl-v:execute(bat {+})'"

# less/man colors
# export DICS="/usr/share/stardict/dic/"
export LESS=-R
LESS_TERMCAP_mb="$(printf '%b' '[1;31m')"; export LESS_TERMCAP_mb
LESS_TERMCAP_md="$(printf '%b' '[1;36m')"; export LESS_TERMCAP_md
LESS_TERMCAP_me="$(printf '%b' '[0m')"; export LESS_TERMCAP_me
LESS_TERMCAP_so="$(printf '%b' '[01;44;33m')";export LESS_TERMCAP_so
LESS_TERMCAP_se="$(printf '%b' '[0m')"; export LESS_TERMCAP_se
LESS_TERMCAP_us="$(printf '%b' '[1;32m')"; export LESS_TERMCAP_us
LESS_TERMCAP_ue="$(printf '%b' '[0m')"; export LESS_TERMCAP_ue

[ ! -f "${XDG_CONFIG_HOME:-$HOME/.config}/shell/shortcutrc" ] && shortcuts >/dev/null 2>&1 &
# echo "$0" | grep "bash$" >/dev/null && [ -f ~/.bashrc ] && source "$HOME/.bashrc"

if [ -f "${XDG_CONFIG_HOME:-$HOME/.config}/lf/icons" ]; then
    LF_ICONS=$(sed ~/.config/lf/icons \
                -e '/^[ \t]*#/d'       \
                -e '/^[ \t]*$/d'       \
                -e 's/[ \t]\+/=/g'     \
                -e 's/$/ /')
    LF_ICONS="${LF_ICONS//$'\n'/:}"
    export LF_ICONS
fi

# Start graphical server on user's current tty if not already running.
# [[ -n "$(tty)" && -z $(pgrep -u $USER "\bXorg$") ]] && exec startx
[ "$(tty)" = "/dev/tty1" ] && ! pidof -s Xorg >/dev/null 2>&1 && exec startx "$XINITRC"

# Switch escape and caps if tty:
sudo -n loadkeys ~/.config/shell/ttymaps.kmap 2>/dev/null
