#!/bin/sh

case $(hostname) in
    VoiD)
        export BROWSER="librewolf"
        export BROWSER2="qutebrowser"
        xrandr --output HDMI-0 --primary --auto --output DVI-D-0 --off
        xrdb ${XDG_CONFIG_HOME:-$HOME/.config}/x11/xresources &
        doas intel-undervolt apply &
        ;;
    vDR)
        export BROWSER="qutebrowser"
        doas intel-undervolt apply &
        xbacklight -set 20 &
        libinput-gestures-setup start &
        bluetooth off &
        ;;
    v)
        export BROWSER="librewolf"
        libinput-gestures-setup start
        ;;
esac

remaps &
setbg &
numlockx &
timeOnPc start &
blacklist on &
notify-send -i "${XDG_PICTURES_DIR:-$HOME/Storage/Pictures}/UserImg.jpg" "«Welcome»" "$(date)"
# xrdb ${XDG_CONFIG_HOME:-$HOME/.config}/x11/xresources &
doas tlp start
echo "\a" >/dev/tty5 # beep
