#!/bin/sh

case $(hostname) in
    VoiD)
        xrdb ${XDG_CONFIG_HOME:-$HOME/.config}/x11/xresources & xrdbpid=$!
        export BROWSER="librewolf"
        export BROWSER2="qutebrowser"
        xrandr --output HDMI-0 --primary --auto --output DVI-D-0 --off
        [ -n "$xrdbpid" ] && wait "$xrdbpid"
        ;;
    vDR)
        export BROWSER="qutebrowser"
        export BROWSER2="librewolf"
        xbacklight -set 20 &
        libinput-gestures-setup start &
        bluetooth off &
        ;;
    void)
        export BROWSER="librewolf"
        export BROWSER2="qutebrowser"
        libinput-gestures-setup start &
        ;;
esac

remaps &
setbg &
numlockx &
sysact Start &
