import = ["/home/davide/.config/alacritty/dark.toml"]
live_config_reload = true

[colors]
draw_bold_text_with_bright_colors = false

[cursor]
unfocused_hollow = true

[font]
size = 10

[font.bold]
family = "IosevkaTerm Nerd Font Propo"
style = "ExtraBold"

[font.glyph_offset]
x = 0
y = 0

[font.italic]
family = "IosevkaTerm Nerd Font Propo"
style = "Italic"

[font.normal]
family = "IosevkaTerm Nerd Font Propo"
style = "Bold"

[font.offset]
x = 1
y = 1

[[hints.enabled]]
action = "Copy"
hyperlinks = true
post_processing = true
regex = "(ipfs:|ipns:|magnet:|mailto:|gemini:|gopher:|https:|http:|news:|file:|git:|ssh:|ftp:)[^\u0000-\u001F\u007F-<>\"\\s{-}\\^⟨⟩`]+"

[hints.enabled.binding]
key = "Y"
mods = "Control|Shift"

[hints.enabled.mouse]
enabled = true
mods = "None"

[[hints.enabled]]
hyperlinks = true
post_processing = true
regex = "(ipfs:|ipns:|magnet:|mailto:|gemini:|gopher:|https:|http:|news:|file:|git:|ssh:|ftp:)[^\u0000-\u001F\u007F-<>\"\\s{-}\\^⟨⟩`]+"

[hints.enabled.binding]
key = "O"
mods = "Control|Shift"

[hints.enabled.command]
program = "$BROWSER"

[hints.enabled.mouse]
enabled = true
mods = "None"

[[keyboard.bindings]]
action = "ResetFontSize"
key = "Key0"
mods = "Alt"

[[keyboard.bindings]]
action = "IncreaseFontSize"
key = "Equals"
mods = "Alt"

[[keyboard.bindings]]
action = "IncreaseFontSize"
key = "Plus"
mods = "Alt"

[[keyboard.bindings]]
action = "DecreaseFontSize"
key = "Minus"
mods = "Alt"

[[keyboard.bindings]]
action = "DecreaseFontSize"
key = "NumpadSubtract"
mods = "Control"

[[keyboard.bindings]]
action = "SpawnNewInstance"
key = "N"
mods = "Alt"

[scrolling]
history = 10000
multiplier = 10

[selection]
save_to_clipboard = false
semantic_escape_chars = ",│`|:\"' ()[]{}<>"

[window]
decorations = "None"
opacity = 1

[window.dimensions]
columns = 150
lines = 40

[window.padding]
x = 2
y = 2
