from libqtile import bar, widget
from colors import dracula

colorscheme = dracula()
(
    colors,
    background,
    foreground,
    workspace,
    foregroundTwo,
) = colorscheme

main_bar = bar.Bar(
    [
        widget.GroupBox(
            padding=4,
            active=colors[2],
            inactive=colors[1],
            highlight_color=[background, workspace],
            this_screen_border=colors[2],
            this_current_screen_border=colors[2],
            other_screen_border=colors[2],
            other_current_screen_border=colors[2],
            highlight_method="line",
            hide_unused=True,
        ),
        widget.TextBox(
            text="\u25e2",
            padding=0,
            fontsize=50,
            background=background,
            foreground=workspace,
        ),
        widget.CurrentLayout(
            background=workspace,
        ),
        widget.TextBox(
            text="\u25e2",
            padding=0,
            fontsize=50,
            background=workspace,
            foreground=background,
        ),
        widget.Spacer(
            length=20,
        ),
        widget.Chord(background=background),
        widget.WindowCount(foreground=colors[7]),
        widget.WindowName(
            foreground=colors[8],
        ),
        # widget.WindowTabs(
        #     selected=('<u>« ',' »</u>'),
        #     separator='      ',
        #     foreground=colors[8],
        #     # background=colors[2],
        # ),
        widget.TextBox(
            text="\u25e2",
            padding=0,
            fontsize=50,
            background=background,
            foreground=foregroundTwo,
        ),
        widget.TextBox(
            text="\u25e2",
            padding=0,
            fontsize=50,
            background=foregroundTwo,
            foreground=foregroundTwo,
        ),
        widget.Prompt(
            bell_style="visual",
            cursorblink=0.5,
            fontsize=18,
            prompt="&:",
            foreground=colors[9],
            background=foregroundTwo,
        ),
        # widget.GenPollCommand(
        #     update_interval=10,
        #     cmd=os.path.expanduser("~/.local/bin/statusbar/sb-music"),
        #     foreground=colors[9],
        #     background=foregroundTwo,
        # ),
        # widget.Mpd2(
        #     status_format='{play_status} [{artist:.15s}]-[{album:.15s}]-[{title:.30s}]',
        #     idle_message="mpd",
        #     color_progress="#9497aa",
        #     update_interval=10,
        #     foreground=colors[9],
        #     background=foregroundTwo,
        # ),
        widget.Load(
            update_interval=3,
            format="{time}:{load:.2f}",
            foreground=colors[4],
            background=foregroundTwo,
        ),
        widget.CPU(
            format="{load_percent:-2.1f}% {freq_current}GHz",
            update_interval=3,
            foreground=colors[5],
            background=foregroundTwo,
        ),
        # widget.CPUGraph(
        #     frequency=5,
        #     graph_color=colors[8],
        #     background=foregroundTwo,
        # ),
        widget.ThermalSensor(
            update_interval=30,
            format=" {temp:.0f}{unit}",
            tag_sensor="Package id 0",
            foreground=colors[6],
            background=foregroundTwo,
        ),
        widget.NvidiaSensors(
            update_interval=30,
            # format=' {temp:.0f}{unit}',
            gpu_bus_id="01:00.0",
            tag_sensor="Package id 0",
            foreground=colors[6],
            background=foregroundTwo,
        ),
        widget.Memory(
            update_interval=15,
            format=" {MemUsed:.0f}{ms}/{SwapUsed:.0f}{ms}",
            foreground=colors[7],
            background=foregroundTwo,
        ),
        # widget.MemoryGraph(
        #     frequency=5,
        #     graph_color=colors[8],
        #     background=foregroundTwo,
        # ),
        # widget.Wlan(
        #     disconnected_message='❌',
        #     format='{essid} {percent:2.0%}',
        #     update_interval=10,
        #     foreground=colors[4],
        #     background=foregroundTwo,
        # ),
        widget.HDDBusyGraph(
            frequency=5,
            graph_color=colors[8],
            background=foregroundTwo,
        ),
        widget.Volume(
            fmt=" {}",
            update_interval=3,
            step=2,
            foreground=colors[8],
            background=foregroundTwo,
            # fmt=" {}"
        ),
        widget.Net(
            fmt=" {}",
            format='{down:.2f}{down_suffix} ↓↑ {up:.2f}{up_suffix}',
            update_interval=3,
            foreground=colors[9],
            background=foregroundTwo,
        ),
        # widget.NetGraph(
        #     frequency=5,
        #     graph_color=colors[8],
        #     background=foregroundTwo,
        # ),
        # widget.Backlight(
        #     update_interval = 15,
        #     foreground=colors[8],
        #     background=foregroundTwo,
        #     ),
        # widget.Battery(
        #     update_interval=15,
        #     format='{char} {percent:2.0%} {hour:d}:{min:02d} {watt:.2f} W',
        #     low_precentage=0.35,
        #     charge_char='',
        #     discharge_char='',
        #     empty_char='',
        #     foreground=colors[6],
        #     background=foregroundTwo,
        #      ),
        widget.TextBox(
            text="\u25e2",
            padding=0,
            fontsize=50,
            background=foregroundTwo,
            foreground=workspace,
        ),
        widget.Systray(background=workspace, foreground=background),
        widget.TextBox(
            text="\u25e2",
            padding=0,
            fontsize=50,
            background=workspace,
            foreground=background,
        ),
        widget.Clock(
            format=" %V %a %d/%B/%y",
            update_interval=3600,
            foreground=colors[10],
            background=background,
        ),
        widget.Clock(
            format=" %T",
            update_interval=1,
            foreground=colors[2],
            background=background,
        ),
        widget.Pomodoro(
            update_interval=1,
            prefix_active=" ",
            prefix_break="🛑",
            prefix_long_break="🛑🛑",
            prefix_inactive="🔃",
            # prefix_paused=️'',
            foreground=colors[1],
            background=background,
            color_active=colors[4],
            color_inactive=colors[6],
        ),
    ],
    17,
)

#     Screen(
#         wallpaper="~/.local/share/bg",
#         wallpaper_mode="stretch",
#         top=bar.Bar(
#             [
#                 widget.GroupBox(
#                     padding=4,
#                     active=colors[2],
#                     inactive=colors[1],
#                     highlight_color=[background, workspace],
#                     this_screen_border=colors[2],
#                     this_current_screen_border=colors[2],
#                     other_screen_border=colors[2],
#                     other_current_screen_border=colors[2],
#                     highlight_method="line",
#                     hide_unused=True,
#                 ),
#                 widget.TextBox(
#                     text="\u25e2",
#                     padding=0,
#                     fontsize=50,
#                     background=background,
#                     foreground=workspace,
#                 ),
#                 widget.CurrentLayout(
#                     scale=0.7,
#                     background=workspace,
#                 ),
#                 widget.TextBox(
#                     text="\u25e2",
#                     padding=0,
#                     fontsize=50,
#                     background=workspace,
#                     foreground=background,
#                 ),
#                 widget.WindowCount(foreground=colors[7]),
#                 widget.WindowName(
#                     foreground=colors[8],
#                 ),
#                 # widget.WindowTabs(
#                 #     selected=('<u>« ',' »</u>'),
#                 #     separator='      ',
#                 #     foreground=colors[8],
#                 #     # background=colors[2],
#                 # ),
#                 widget.TextBox(
#                     text="\u25e2",
#                     padding=0,
#                     fontsize=50,
#                     background=background,
#                     foreground=foregroundTwo,
#                 ),
#                 # widget.Mpd2(
#                 #     status_format='{play_status} [{artist:.15s}]-[{album:.15s}]-[{title:.30s}]',
#                 #     idle_message="mpd",
#                 #     color_progress="#9497aa",
#                 #     update_interval=10,
#                 #     foreground=colors[9],
#                 #     background=foregroundTwo,
#                 # ),
#                 # widget.Net(
#                 #     fmt=' {}',
#                 #     update_interval=2,
#                 #     foreground=colors[9],
#                 #     background=foregroundTwo,
#                 # ),
#                 widget.TextBox(
#                     text="\u25e2",
#                     padding=0,
#                     fontsize=14,
#                     background=foregroundTwo,
#                     foreground=foregroundTwo,
#                 ),
#                 widget.Prompt(
#                     bell_style="visual",
#                     cursorblink=0.5,
#                     fontsize=18,
#                     prompt="&:",
#                     foreground=colors[9],
#                     background=foregroundTwo,
#                 ),
#                 # widget.Countdown(
#                 #     # format='{D}d {H}h {M}m {S}s',
#                 #     date=datetime(2023, 10, 5, 0, 0, 0, 0),
#                 #     foreground=colors[3],
#                 #     background=foregroundTwo,
#                 #     color_active=colors[4],
#                 #     color_inactive=foregroundTwo
#                 # ),
#                 # widget.Backlight(
#                 #     update_interval = 15,
#                 #     foreground=colors[8],
#                 #     background=foregroundTwo,
#                 #     ),
#                 # widget.Battery(
#                 #     update_interval=15,
#                 #     format='{char} {percent:2.0%} {hour:d}:{min:02d} {watt:.2f} W',
#                 #     low_precentage=0.35,
#                 #     charge_char='',
#                 #     discharge_char='',
#                 #     empty_char='',
#                 #     foreground=colors[6],
#                 #     background=foregroundTwo,
#                 #      ),
#                 widget.HDDBusyGraph(
#                     frequency=5,
#                     start_pos="top",
#                     graph_color=colors[8],
#                     background=foregroundTwo,
#                 ),
#                 widget.TextBox(
#                     text="\u25e2",
#                     padding=0,
#                     fontsize=50,
#                     background=foregroundTwo,
#                     foreground=background,
#                 ),
#                 widget.Clipboard(
#                     # update_interval=1,
#                     foreground=colors[3],
#                     background=background,
#                     color_active=colors[4],
#                     color_inactive=foregroundTwo,
#                 ),
#             ],
#             20,
#         ),
#     ),
# ]
