#!/bin/sh

export DISPLAY=:0
export XAUTHORITY="$HOME/.config/Xauthority"
exec xautolock -time 15 -notify 180 -notifier "notify-send -u critical -t 180000 'System will be locked' '3 minute left'" -locker 'doas zzz'
