theme = "dracula"
client_id = "65b708073fc0480ea92a077233ca87bd"
client_port = 9080
playback_format = "{track} • {artists} • {album} • {metadata}"
tracks_playback_limit = 50
app_refresh_duration_in_ms = 32
playback_refresh_duration_in_ms = 0
page_size_in_rows = 20
play_icon = "▶"
pause_icon = "▌▌"
liked_icon = "♥"
border_type = "Double"
progress_bar_type = "Rectangle"
progress_bar_position = "Bottom"
playback_window_position = "Bottom"
cover_img_length = 16
cover_img_width = 16
cover_img_scale = 1.0
pause_on_startup = false
playback_window_width = 6
enable_media_control = true
enable_streaming = "Always"
enable_notify = false
enable_cover_image_cache = true
default_device = "spotify-player"
notify_streaming_only = false

[copy_command]
command = "wl-copy"

[notify_format]
summary = "{track} • {artists}"
body = "{album}"

[device]
name = "spotify-player"
device_type = "computer"
volume = 80
bitrate = 320
audio_cache = true
normalization = true
autoplay = true

[[actions]]
action = "GoToArtist"
key_sequence = "g A"
[[actions]]
action = "GoToAlbum"
key_sequence = "g B"
target = "PlayingTrack"
[[actions]]
action="ToggleLiked"
key_sequence="C-l"
