#!/bin/sh

case "$(grep "^NAME=" /etc/os-release | cut -f2 -d'=')" in
Void | \"Void\")
    . "${XDG_CONFIG_HOME:-$HOME/.config}/shell/modules/void"
    ;;
NixOS | \"NixOS\")
    . "${XDG_CONFIG_HOME:-$HOME/.config}/shell/modules/nixos"
    ;;
Ubuntu | Armbian | \"Ubuntu\" | \"Armbian\") ;;
esac

alias \
    cclip="wl-copy" \
    pclip="wl-paste" \
    chrome="chromium --ozone-platform=wayland --enable-features=AcceleratedVideoDecodeLinuxGL --enable-features=VaapiVideoDecoder,VaapiIgnoreDriverChecks,Vulkan,DefaultANGLEVulkan,VulkanFromANGLE --force-device-scale-factor=1.0 --gtk-version=4 --enable-features=WaylandPerSurfaceScale,WaylandUiScale" \
    f="lf" \
    hclip="cliphist list | fzf | cliphist decode | wl-copy" \
    mpc="mpc --host=\"\$MPD_HOST\"" \
    wt="wtwitch"

# Override GNU defaults
alias \
    bc="bc -l" \
    cp="cp -iv" \
    df="df -h" \
    du="du -h" \
    free="free -h" \
    ka="killall" \
    mkd="mkdir -pv" \
    mv="mv -iv" \
    rm="rm -vI" \
    rsync="rsync -urvhrP --info=progress2"
# unxz="unxz -v"

# Colorize commands
alias \
    bathelp='bat --plain --language=help' \
    ccat="bat --pager=never" \
    diff="diff --color=auto" \
    grep="grep --color=auto" \
    ip='ip -color=auto' \
    l='eza -lg --icons --group-directories-first' \
    ll='eza -lag --icons --group-directories-first'

# Abbreviations
alias \
    E="\$VISUAL" \
    d2p="find \$HOME/dwn -maxdepth 1 -mindepth 1 -type f \( -iname \"*.jpg\" -o -iname \"*.png\" -o -iname \"*.webm\" -o -iname \"*.gif\" -o -iname \"*.webp\" -o -iname \"*.avif\" \) -exec mv {} \"\${XDG_PICTURES_DIR:-\$HOME/pic}/1Sort\" \;" \
    e="\$EDITOR" \
    irssi="irssi --config=\"\$XDG_CONFIG_HOME\"/irssi/config -- home=\"\$XDG_DATA_HOME\"/irssi" \
    locate="locate -d \"\$HOME/.local/updatedb\" -ri" \
    mpa="mpv --no-video --audio-client-name=mpv-audio " \
    pip="python3 -m pip" \
    pips="python3 -m pip_search" \
    ferdium="ferdium --enable-features=UseOzonePlatform,WaylandWindowDecorations --ozone-platform-hint=auto >/dev/null 2>&1" \
    pw="pipe-viewer" \
    q="exit" \
    s="doas" \
    scl="systemctl" \
    sclu="systemctl --user" \
    smi="doas make install" \
    udc="udisksctl" \
    v="nvim" \
    watch="watch -pcb" \
    x="sxiv -ft *" \
    zt="zathura"

alias \
    smooth-brown="nix-shell -p sox --run 'sox -c2 --null -d synth 0:60 brownnoise band -n 210.0 1000.0 tremolo 0.0166 70.0 reverb 40.0 fade q 0.005 0:60 0.005 repeat -'" \
    smooth-white="play -n -c1 synth whitenoise lowpass -1 120 lowpass -1 120 lowpass -1 120 gain +14" \
    deep-smooth-white="play -n synth whitenoise band -n 100 24 band -n 300 100 gain +20" \
    bells="mpv --no-config --no-video --audio-client-name=mpv-audio 'http://icecast.spc.org:8000/longplayer'" \
    space-void="play -n -c1 synth whitenoise band -n 100 20 band -n 50 20 gain +25  fade h 1 864000 1" \
    space-engine="play -n -c1 synth whitenoise lowpass -1 120 lowpass -1 120 lowpass -1 120 gain +14"

# Miscellaneous
alias \
    ffmpeg="ffmpeg -hide_banner" \
    ref="shortcuts >/dev/null; source \${XDG_CONFIG_HOME:-\$HOME/.config}/shell/shortcutrc ; source \${XDG_CONFIG_HOME:-\$HOME/.config}/shell/zshnameddirrc" \
    mpv-update-plugins="find \"\$XDG_CONFIG_HOME/mpv/modules\" -type d -exec test -e '{}/.git' ';' -print0 | xargs -I {} -0 git -C {} pull" \
    zsh-update-plugins="find \"\$ZDOTDIR/plugins\" -type d -exec test -e '{}/.git' ';' -print0 | xargs -I {} -0 git -C {} pull" \
    search_commit="fzf --multi --ansi --preview='head -50 {+}' &&
		git log --oneline |
		fzf --multi --ansi --preview='git show {+1}'"

y() {
    set -- "$@" --cwd-file "$(mktemp -t yazi-cwd.XXXXXX)"
    command yazi "$@"
    shift $(($# - 1))
    set -- "$(
        command cat <"$1"
        printf .
        rm -f -- "$1"
    )"
    set -- "${1%.}"
    [ "$1" != "$PWD" ] && [ -d "$1" ] && command cd -- "$1" || exit
}

batdiff() {
    git diff --name-only --relative --diff-filter=d | xargs bat --diff
}

help() {
    "$@" --help 2>&1 | bathelp
}

battail() {
    tail -f "$@" | bat --paging=never -l log
}

randstring() {
    tr -dc A-Za-z0-9 </dev/urandom | head -c "${1:-16}"
    echo
}

randpw() {
    openssl rand -base64 "${1:-32}"
}

dict() {
    curl dict://dict.org/d:\\"$*"
}

yta() {
    mpv --no-video --audio-client-name=mpv-audio --force-window=no --ytdl-format=bestaudio ytdl://ytsearch:"$*"
}

modules_update() {
    find "$1" -type d -exec test -e '{}/.git' ';' -print0 |
        xargs -I {} -0 git -C {} pull origin master
}

[ -f "$XINITRC" ] && alias startx="startx \$XINITRC"

[ -x "$(command -v nvim)" ] && alias vim="nvim" vimdiff="nvim -d"
