#!/bin/sh

# Override GNU defaults
alias \
    bc="bc -l" \
    cp="cp -iv" \
    df="df -h" \
    du="du -h" \
    free="free -h" \
    ka="killall" \
    mkd="mkdir -pv" \
    mv="mv -iv" \
    rm="rm -vI" \
    rsync="rsync -uavhrP --info=progress2"
# unxz="unxz -v"

# Colorize commands
alias \
    ccat="bat --pager=never" \
    diff="diff --color=auto" \
    egrep='egrep --color=auto' \
    fgrep='fgrep --color=auto' \
    grep="grep --color=auto" \
    ip='ip -color=auto' \
    l='exa -l --icons --group-directories-first' \
    ll='exa -la --icons --group-directories-first'

# Abbreviations
alias \
    2f="tmux split -h lfcd; lfcd" \
    e="\$EDITOR" \
    E="\$VISUAL" \
    f="lfcd" \
    pw="pipe-viewer" \
    cpuperf="sudo cpupower frequency-set --governor performance" \
    cpusave="sudo cpupower frequency-set --governor powersave" \
    pip="python3 -m pip" \
    pips="python3 -m pip_search" \
    q="exit" \
    s="doas" \
    scl="systemctl" \
    sclu="systemctl --user" \
    smi="doas make install" \
    spd="librespot \
            --c ~/.cache/librespot \
            --backend alsa \
            --cache-size-limit 1G \
            --name \"$(hostname)\" \
            --device-type computer \
            --initial-volume 100 \
            --enable-volume-normalisation \
            --normalisation-pregain -7 \
            --bitrate 320" \
    v="nvim" \
    trr="transmission-remote" \
    udc="udisksctl" \
    updatedb="updatedb \
        --localuser=davide \
        --localpaths=\"\$HOME\" --output=\"\$HOME/.local/updatedb\" \
        --prunepaths=\"\$HOME/Packages \$HOME/MATLAB \$HOME/sources .*/\..*\"" \
    locate="locate -d \"\$HOME/.local/updatedb\" -ri" \
    x="sxiv -ft *" \
    xclip="xclip -selection clipboard" \
	yt="yt-dlp --embed-metadata -i" \
    zt="zathura"
# samedir="setsid -f $TERMINAL >/dev/null 2>&1" \
# sudo="doas" \

sbmks() {
    xclip  -selection clipboard -o >> "$HOME/.config/qutebrowser/quickmarks"

}
bmks() {
    bookmark_file="$XDG_CONFIG_HOME/qutebrowser/quickmarks"
    description="$(cut -d' ' -f2- "$bookmark_file" | fzf)"
    link="$(grep "$description" "$bookmark_file")"
    [ "$(echo "$link" | wc -l )" -gt 1 ] && echo "Nothing selected. Exiting" && return
    setsid -f "$BROWSER" "$link" >/dev/null 2>&1 &
}

lynxs() {
    lynx -cfg="$HOME/.config/lynx/lynx.cfg" "https://searx.be/search?q=$1"
}

lynxa() {
    lynx -cfg="$HOME/.config/lynx/lynx.cfg" "$*"
}

# fuzzy find
# alias \
#     vfc="find \$HOME/.config/ -maxdepth 1 | fzf | xargs -r -I % \$EDITOR %" \
#     vfd="find \$HOME/.local/src/dotfiles/ | fzf | xargs -r -I % \$EDITOR %" \
#     vfs="find \$HOME/.local/bin/ | fzf | xargs -r -I % \$EDITOR %" \
#     vfz="find \$HOME/.config/zsh/ | fzf | xargs -r -I % \$EDITOR %"

fzfopen() {
    f="$(locate -i "$HOME/$1" | fzf)"
    xdg-open "$f"
}

batdiff() {
    git diff --name-only --relative --diff-filter=d | xargs bat --diff
}

# git
# alias \
    # g="git" \
    # ga="git add" \
    # gc="git commit -m" \
    # gd="git pull" \
    # gs="git status" \
    # gu="git push" \
    # scommitf="fzf --multi --ansi --preview='head -20 {+}' &&
	# 	git log --oneline |
	# 	fzf --multi --ansi --preview='git show {+1}'"
# gua="git remote | xargs -L1 git push --all"

gcl() {
    git clone "$(xclip -selection clipboard -o)"
}

# xbps-install & upgrade
alias \
    xbi="doas xbps-install -S" \
    xu="doas xbps-install -Su"

sxi() {
    LIST="$(xbps-query -Rs "$1" | fzf | cut -d' ' -f2)"
    [ -z $LIST ] && return
    doas xbps-install -Sy $LIST
}

# xbps-query
alias \
    xq="xbps-query -Rs" \
    xgot="xbps-query -l | fzf"

sxq() {
    xbps-query -Rs "$1" | fzf
}

tso(){
    setsid -f "$(ts |
        awk -v n=6 '{ for (i=n; i<=NF; i++) printf "%s%s", $i, (i<NF ? OFS : ORS)}' |
        fzf |
        cut -d']' -f2)"
}

# xbps-remove
alias \
    xr="doas xbps-remove -R" \
    sxr="xbps-query -l | fzf | cut -d ' ' -f 2 | xargs -r -I % doas xbps-remove -Ry %"

# Miscellaneous
alias \
    cleanupdates="doas vkpurge rm all; xr -Ooy" \
    dwmrefresh="kill -HUP \$(pidof -s dwm)" \
    ffmpeg="ffmpeg -hide_banner" \
    ref="shortcuts >/dev/null; source \${XDG_CONFIG_HOME:-\$HOME/.config}/shell/shortcutrc ; source \${XDG_CONFIG_HOME:-\$HOME/.config}/shell/zshnameddirrc" \
    zsh-update-plugins="find \"\$ZDOTDIR/plugins\" -type d -exec test -e '{}/.git' ';' -print0 | xargs -I {} -0 git -C {} pull"
# mpv="mpv --input-ipc-server=/tmp/mpvsoc$(date +%s)" \

[ -f "$XINITRC" ] && alias startx="startx \$XINITRC"

[ -x "$(command -v nvim)" ] && alias vim="nvim" vimdiff="nvim -d"
