#!/bin/sh

case "$(printenv XDG_SESSION_TYPE)" in
    wayland)
        alias \
            2f="tmux split -h lf; lf" \
            f="lf"
            # cclip="wl-copy" \
            # pclip="wl-paste"
        ;;
    tty | x11)
        alias \
            2f="tmux split -h lfcd; lfcd" \
            f="lfcd"
            # cclip="xclip -selection clipboard" \
            # pclip="xclip -selection clipboard -o"
        ;;
esac

case "$(grep "^NAME=" /etc/os-release | cut -f2 -d'=')" in
    Void|\"Void\")
        alias \
            xbi="doas xbps-install -S" \
            xu="doas xbps-install -Su" \
            xr="doas xbps-remove -R" \
            sxr="xbps-query -l | fzf | cut -d ' ' -f 2 | xargs -r -I % doas xbps-remove -Ry %"

        sxi() {
            LIST="$(xbps-query -Rs "$1" | fzf | cut -d' ' -f2)"
            [ -z $LIST ] && return
            doas xbps-install -Sy $LIST
        }

        alias \
            xq="xbps-query -Rs" \
            xgot="xbps-query -l | fzf"

        sxq() {
            xbps-query -Rs "$1" | fzf
        }
        ;;
    NixOS|\"NixOS\")
        alias \
            animdl="~/Packages/python/ani/bin/animdl" \
            hm='home-manager' \
            nsh='nix-shell -p' \
            unclt='systemctl --user start unclutter.service' \
            qtilelog='less -N +F $HOME/.local/share/qtile/qtile.log' \
            wt='wtwitch'

        hms() {
            DIR="$HOME/.mozilla/firefox/nixhm"
            rm "$DIR/containers.json"
            mv "$DIR/chrome/userChrome.css" "$DIR/chrome/userChrome0.css"
            mv "$DIR/chrome/userContent.css" "$DIR/chrome/userContent0.css"
            home-manager switch
            mv "$DIR/chrome/userChrome0.css" "$DIR/chrome/userChrome.css"
            mv "$DIR/chrome/userContent0.css" "$DIR/chrome/userContent.css"
        }

        hmu() {
            cd "$HOME/.config/home-manager" &&
                nix flake update &&
                cd "$HOME" &&
                home-manager switch 2>&1 |
                    tee "$HOME/.local/hm_last.log"
        }
        ;;
    Ubuntu|Armbian|\"Ubuntu\"|\"Armbian\")
        ;;
esac

# Override GNU defaults
alias \
    bc="bc -l" \
    cp="cp -iv" \
    df="df -h" \
    du="du -h" \
    free="free -h" \
    ka="killall" \
    mkd="mkdir -pv" \
    mv="mv -iv" \
    rm="rm -vI" \
    rsync="rsync -uavhrP --info=progress2"
# unxz="unxz -v"

# Colorize commands
alias \
    ccat="bat --pager=never" \
    diff="diff --color=auto" \
    egrep='egrep --color=auto' \
    fgrep='fgrep --color=auto' \
    grep="grep --color=auto" \
    ip='ip -color=auto' \
    l='eza -l --icons --group-directories-first' \
    ll='eza -la --icons --group-directories-first'

# Abbreviations
alias \
    E="\$VISUAL" \
    doomupdate="doom sync && doom sync -u && doom upgrade && doom purge > ~/.local/doom-upgrade" \
    e="\$EDITOR" \
    irssi="irssi --config=\"\$XDG_CONFIG_HOME\"/irssi/config -- home=\"\$XDG_DATA_HOME\"/irssi" \
    locate="locate -d \"\$HOME/.local/updatedb\" -ri" \
    mpa="mpv --no-video --audio-client-name=mpv-audio " \
    pip="python3 -m pip" \
    pips="python3 -m pip_search" \
    pw="pipe-viewer" \
    q="exit" \
    s="doas" \
    scl="systemctl" \
    sclu="systemctl --user" \
    smi="doas make install" \
    trr="transmission-remote" \
    trrq="transmission-remote --exit" \
    udc="udisksctl" \
    v="nvim" \
    watch="watch -pcb" \
    x="sxiv -ft *" \
    zt="zathura"

alias \
    smooth-brown="sox -c2 --null -d synth 0:60 brownnoise band -n 210.0 1000.0 tremolo 0.0166 70.0 reverb 40.0 fade q 0.005 0:60 0.005 repeat -" \
    smooth-white="play -n -c1 synth whitenoise lowpass -1 120 lowpass -1 120 lowpass -1 120 gain +14" \
    deep-smooth-white="play -n synth whitenoise band -n 100 24 band -n 300 100 gain +20" \
    bells="mpv --no-config --no-video --audio-client-name=mpv-audio 'http://icecast.spc.org:8000/longplayer'" \
    space-void="play -n -c1 synth whitenoise band -n 100 20 band -n 50 20 gain +25  fade h 1 864000 1" \
    space-engine="play -n -c1 synth whitenoise lowpass -1 120 lowpass -1 120 lowpass -1 120 gain +14"

trrd() {
    tun0="$(ip a show dev tun0 scope global | awk '/inet/ {print $2}' | awk -F '/' '{print $1}')"
    transmission-daemon --bind-address-ipv4="$(echo "$tun0" | head -n1)" --bind-address-ipv6="$(echo "$tun0" | tail -n1)"
}

dict() {
    curl dict://dict.org/d:\$@
}

yta() {
    mpv --no-video --audio-client-name=mpv-audio --force-window=no --ytdl-format=bestaudio ytdl://ytsearch:"$*"
}

modules_update() {
    find "$1" -type d -exec test -e '{}/.git' ';' -print0 |
        xargs -I {} -0 git -C {} pull origin master
}

alias \
    search_commit="fzf --multi --ansi --preview='head -50 {+}' &&
		git log --oneline |
		fzf --multi --ansi --preview='git show {+1}'"

# Miscellaneous
alias \
    ffmpeg="ffmpeg -hide_banner" \
    ref="shortcuts >/dev/null; source \${XDG_CONFIG_HOME:-\$HOME/.config}/shell/shortcutrc ; source \${XDG_CONFIG_HOME:-\$HOME/.config}/shell/zshnameddirrc" \
    mpv-update-plugins="find \"\$XDG_CONFIG_HOME/mpv/modules\" -type d -exec test -e '{}/.git' ';' -print0 | xargs -I {} -0 git -C {} pull" \
    zsh-update-plugins="find \"\$ZDOTDIR/plugins\" -type d -exec test -e '{}/.git' ';' -print0 | xargs -I {} -0 git -C {} pull"

[ -f "$XINITRC" ] && alias startx="startx \$XINITRC"

[ -x "$(command -v nvim)" ] && alias vim="nvim" vimdiff="nvim -d"
