#!/bin/sh

# Override GNU defaults
alias \
	bc="bc -l" \
	cp="cp -iv" \
	df="df -h" \
	du="du -h" \
	free="free -h" \
	history="fc -rl 0 | fzf" \
	ka="killall" \
	mkd="mkdir -pv" \
	mv="mv -iv" \
	rm="rm -vI" 
	# unxz="unxz -v"

# Colorize commands
alias \
	ccat="highlight --out-format=ansi" \
	diff="diff --color=auto" \
	grep="grep --color=auto"

# Abbreviations
	# bc="bc -l" \
	# sdn="doas shutdown -h now" \
	# spawn="setsid st &" \
	# trem="transmission-remote" \
	# fmpv='find "$HOME/.config/mpv" | fzf | xargs -r -I % "$EDITOR" %' \
alias \
	c.="cd .." \
	cvf='find "$HOME/.config" | fzf +i --algo=v2 | xargs -r -I % "$EDITOR" %' \
	e="$EDITOR" \
	f="$FILE" \
	fl='fzf +i | xargs -r -I % lf %' \
	of='fzf | xargs -r -I % opener %'  \
	q="exit" \
	s="doas" \
	scf='find "$HOME/.local/bin/" | fzf | xargs -r -I % "$EDITOR" %' \
	srf='find "$HOME/.local/src/" | fzf | xargs -r -I % "$EDITOR" %' \
	sudo="doas" \
	t="task" \
	tw="timew" \
	v="$EDITOR" \
	vf='vim -o `fzf`' \
	x="sxiv -ft *" \
	z="zathura"

# git
# alias \
	# g="git" \
	# ga="git add"\
	# gc="git commit -m"\
	# gd="git pull" \
	# gcl='git clone https://github.com/"$1".git ' \
	# gs="git status"\
	# gu="git push" \
	# gua="git remote | xargs -L1 git push --all"

# xbps-install & upgrade
alias \
	xi="doas xbps-install -S" \
	xu="doas xbps-install -Su" \
	sxi='xbps-query -Rs "$1" | fzf | cut -d' ' -f2 | xargs -r -I % doas xbps-install -S %' 

# xbps-query
alias \
	xq="xbps-query -Rs" \
	sxq='xbps-query -Rs "$1" | fzf' \
	xgot="xbps-query -l | fzf" 

# xbps-remove
alias \
	xr="doas xbps-remove -R" \
	sxr='xbps-query -l | fzf | xargs -r -I % doas xbps-remove -R %'

# youtube
# alias \
	# y="straw-viewer"
	# yt="youtube-dl --add-metadata -i" \
	# yta="yt -x -f bestaudio/best" \
	# dlm="youtube-dl --add-metadata -ic --extract-audio --audio-format mp3 --audio-quality 0" \
	# dlv="youtube-dl -ic --add-metadata" \
	# yt="youtube-dl --add-metadata -i -o '%(upload_date)s-%(title)s.%(ext)s'" \
	# yta="yt -x -f bestaudio/best"

# Miscellaneous
alias \
	cleanupdates="doas vkpurge rm all; xr -Ooy" \
	dwmrefresh="kill -HUP $(pidof -s dwm)" \
	ffmpeg="ffmpeg -hide_banner" \
	magit="nvim -c MagitOnly" \
	mpv="mpv --input-ipc-server=/tmp/mpvsoc$(date +%s)" \
	ref="shortcuts >/dev/null; source ${XDG_CONFIG_HOME:-$HOME/.config}/shortcutrc ; source ${XDG_CONFIG_HOME:-$HOME/.config}/zshnameddirrc" 
	# tmux="tmux -f ${XDG_CONFIG_HOME:-$HOME/.config}/tmux/tmux.conf" 

[ -x "$(command -v nvim)" ] && alias vim="nvim" vimdiff="nvim -d"
