# ======================= Settings ======================= {{{
include "../module/waybar.conf"
font pango: IosevkaTermSlab Nerd Font Bold 12
default_orientation auto
xwayland enable
# floating_minimum_size 1280 x 720
# floating_maximum_size 1920 x 1080
# }}}
# ======================= Variables ======================= {{{
set {
    $output_primary            'DVI-I-1'
    $output_secondary          'HDMI-A-1'

    $EDITOR2    $term -T 'temacs' -e emacsclient -nw
    $EDITOR     emacsclient -c
    $BROSWER    "$BROWSER"

    $wph "${XDG_DATA_HOME:-$HOME/.local/share}/mainbg"
    $wpv "${XDG_DATA_HOME:-$HOME/.local/share}/mainbg"
}
# }}}
# ======================= Outputs ======================= {{{
output $output_primary {
    pos 1920 0
    # bg $wph fill
}

output $output_secondary {
    pos 0 0
    # bg $wpv fill
}
# }}}
# ======================= Multi-Monitor ======================= {{{
mode "display" {
    bindsym {
        1                output $output_primary pos 0,0
        2                output $output_primary pos 0,0; output $output_secnodary_vert pos 3840 30 transform 90
        3                output $output_secondary_standalone
        m                exec toggle-screens mono
        d                exec toggle-screens dual
        Return           mode "default"
        Escape           mode "default"
    }
}

workspace {
    1 output $output_primary
    2 output $output_primary
    3 output $output_primary
    4 output $output_primary
    5 output $output_primary
    6 output $output_primary
    7 output $output_primary
    8 output $output_primary
    9 output $output_primary
    0 output $output_primary
    10 output $output_primary
    11 output $output_primary
    12 output $output_primary
    13 output $output_primary
    14 output $output_primary
    15 output $output_primary
    16 output $output_primary
    17 output $output_primary
    18 output $output_primary
    19 output $output_primary
}
#

bindsym {
    $M+a                      workspace number 20
    $M+s                      workspace number 21
    $M+d                      workspace number 22
    $M+f                      workspace number 23
    $M+g                      workspace number 24

    $M+$C+a                   move container to workspace number 20
    $M+$C+s                   move container to workspace number 21
    $M+$C+d                   move container to workspace number 22
    $M+$C+f                   move container to workspace number 23
    $M+$C+g                   move container to workspace number 24

    $A+a                      focus parent
    $A+$C+a                   focus child

    $A+s                      sticky toggle
    $A+$C+s                   layout stacking

    $A+d                      exec $drun
    $A+$C+d                   exec via -r
    $A+$S+d                   exec via -a
    $A+$C+$S+d                mode "launcher"

    $A+f                      $maximize
    $A+$C+f                   fullscreen

    $A+g                      gaps toggle
    $A+$C+g                   mode $gaps_editor
}
# }}}
# ======================= Autostart ======================= {{{
exec {
    dbus-update-activation-environment --systemd WAYLAND_DISPLAY XDG_CURRENT_DESKTOP=sway

    wlsunset -t 2400 -T 6500 -S 06:30 -s 20:00 -d 1800

    sleep 20 && emacsclient -e '(doom/quickload-session t)' -c
    # sleep 20 && $term -T 'term-emacs' -e emacsclient -e '(doom/load-session t)' -nw &

    swayidle -w \
    timeout 180 'swaymsg "output * dpms off"' resume 'swaymsg "output * dpms on"'
    # timeout 300 'swaylock -f -c 000000' \
    # before-sleep 'swaylock'

    sleep 35 && swaymsg reload && $BROWSER
}
# }}}
