#!/bin/sh

# Example for $XDG_CONFIG_HOME/nsxiv/exec/image-info
# Called by nsxiv(1) whenever an image gets loaded.
# The output is displayed in nsxiv's status bar.
# Arguments:
#   $1: path to image file
#   $2: image width
#   $3: image height

exec 2>/dev/null

s=" | " # field separator
filesize=$(du -Hh -- "$1" | cut -f 1)

echo "${filesize}${s}${2}x${3}${s}${1}"

# tags=$(exiv2 -q pr -pi "$1" | awk '$1~"Keywords" { printf("%s,", $4); }')
# tags=${tags%,}

# echo "${filesize}${s}${geometry}${tags:+$s}${tags}${s}${filename}"
