#!/bin/sh

sv check "$HOME/.local/service/pipewire" >/dev/null || exit 1
[ -r ./conf ] && . ./conf

if [ "${LOGGING_ENABLE:-0}x" = "1x" ] && [ -n "${LOG_LEVEL}" ]; then
    export PIPEWIRE_DEBUG="${LOG_LEVEL}"
fi

sleep 15
exec wireplumber "${OPTS:-}" 2>&1
