output $output_laptop {
    scale 1
    pos 0 0
}

bindsym {
    $M+y                      workspace number 15
    $M+u                      workspace number 16
    $M+i                      workspace number 17
    $M+o                      workspace number 18
    $M+p                      workspace number 19

    $M+q                      workspace number 10
    $M+w                      workspace number 11
    $M+e                      workspace number 12
    $M+r                      workspace number 13
    $M+t                      workspace number 14

    $M+$C+y                   move container to workspace number 15
    $M+$C+u                   move container to workspace number 16
    $M+$C+i                   move container to workspace number 17
    $M+$C+o                   move container to workspace number 18
    $M+$C+p                   move container to workspace number 19

    $M+$C+q                   move container to workspace number 10
    $M+$C+w                   move container to workspace number 11
    $M+$C+e                   move container to workspace number 12
    $M+$C+r                   move container to workspace number 13
    $M+$C+t                   move container to workspace number 14
}
