#!/bin/sh

setopt HIST_IGNORE_ALL_DUPS
HISTFILE="${XDG_CACHE_HOME:-$HOME/.cache}/zsh-history"
HISTSIZE=1000000
SAVEHIST=1000000

# export PATH="$PATH:$(du "$HOME/.local/bin/" | cut -f2 | paste -sd ':' -)"
# export PATH="$PATH:$HOME/.local/share/npm/bin/"
# export PATH="$PATH:$HOME/.local/share/cargo/bin/"
# export PATH="$PATH:$HOME/.local/share/go/bin"
# export PATH=$HOME/.miniconda/bin:$PATH

# export MANPAGER='nvim +Man!'
# export MANWIDTH=999
# export GOPATH=$HOME/.local/share/go

# eval "$(fnm env)"
eval "$(zoxide init zsh)"
# eval "$(pip completion --zsh)"
