#!/bin/zsh

autoload -U colors && colors
autoload -Uz vcs_info
precmd() { vcs_info }

# Format the vcs_info_msg_0_ variable
zstyle ':vcs_info:git:*' formats 'on %b'

setopt PROMPT_SUBST
# PROMPT=" %B%{$fg[magenta]%}%~ %{$fg[blue]%}❯%{$fg[magenta]%}❯%{$fg[red]%}❯%b "
PROMPT=" %B%{$fg[red]%}[%{$fg[yellow]%}%n%{$fg[red]%}@%{$fg[blue]%}%m%{$fg[red]%}] %{$fg[magenta]%}%~%  %{$fg[cyan]%}\${vcs_info_msg_0_} $fg[blue]%}%{$fg[magenta]%}%{$fg[red]%}%b "
RPROMPT='%(?:: %F{1}✘ %?) %F{3}${display_timer}'
# RPROMPT="%(?:: %F{1}✘ %?) \$vcs_info_msg_0_ "
SPROMPT="Correct %F{1}%R%f to %F{2}%r%f [nyae]? "

# TODO look into this for more colors
# https://stevelosh.com/blog/2010/02/my-extravagant-zsh-prompt/
# also ascii escape codes
