#!/bin/zsh
# zmodload zsh/zprof

# some useful options (man zshoptions)
setopt autocd extendedglob nomatch menucomplete
setopt interactive_comments
stty stop undef # Disable ctrl-s to freeze terminal.
zle_highlight=('paste:none')

# beeping is annoying
unsetopt BEEP

# completions
autoload -Uz compinit
zstyle ':completion:*' menu select # zstyle ':completion::complete:lsof:*' menu yes select
zmodload zsh/complist # compinit
_comp_options+=(globdots) # Include hidden files.

autoload -U up-line-or-beginning-search
autoload -U down-line-or-beginning-search
zle -N up-line-or-beginning-search
zle -N down-line-or-beginning-search

# Colors
autoload -Uz colors && colors

# Useful Functions
. "$ZDOTDIR/zsh-functions"

# Normal files to source
zsh_add_file "zsh-exports"
zsh_add_file "zsh-vim-mode"
zsh_add_file "zsh-prompt"

# Load aliases and shortcuts if existent.
[ -f "$HOME/.config/shell/shortcutrc" ] && . "$HOME/.config/shell/shortcutrc"
[ -f "$HOME/.config/shell/aliasrc" ] && . "$HOME/.config/shell/aliasrc"

# Plugins
zsh_add_plugin "Aloxaf/fzf-tab"
zsh_add_plugin "hlissner/zsh-autopair"
zsh_add_plugin "joshskidmore/zsh-fzf-history-search"
zsh_add_plugin "zsh-users/zsh-autosuggestions"
zsh_add_plugin "zsh-users/zsh-syntax-highlighting"
zsh_add_plugin "MichaelAquilina/zsh-auto-notify"
AUTO_NOTIFY_IGNORE+=("lf" "f" "nvim" "vim" "emacsclient" "emacs" \
    "tremc" "countdown" "blackrain")
# For more plugins: https://github.com/unixorn/awesome-zsh-plugins
# More completions https://github.com/zsh-users/zsh-completions

# Key-bindings
bindkey "^j" down-line-or-beginning-search # Down
bindkey "^k" up-line-or-beginning-search # Up
bindkey "^n" down-line-or-beginning-search # Down
bindkey "^p" up-line-or-beginning-search # Up
bindkey '^[[P' delete-char
bindkey '^[[3~' delete-char
bindkey '^H' delete-char
bindkey '^s' doas-command-line
bindkey -M vicmd '^[[P' vi-delete-char
bindkey -M vicmd '^e' edit-command-line
bindkey -M visual '^[[P' vi-delete
bindkey -r "^d"
bindkey -r "^u"
bindkey '^[[28;5;9~' autosuggest-execute
bindkey -s '^v' '"$(pclip)"'
bindkey -s '^o' '^ulfcd^M'
bindkey -s '^f' '^ucd "$(dirname "$(fzf)")"^M'
# bindkey -s '^v' 'nvim $(fzf)^M'
bindkey -s '^b' 'vf^M'
bindkey -s '^z' 'zi^M'
bindkey -v '^?' backward-delete-char

bindkey "^y" autosuggest-accept
bindkey "^h" autosuggest-execute

# FZF
[ -f /usr/share/fzf/completion.zsh ] && . /usr/share/fzf/completion.zsh
[ -f /usr/share/fzf/key-bindings.zsh ] && . /usr/share/fzf/key-bindings.zsh
[ -f /usr/share/doc/fzf/examples/completion.zsh ] && . /usr/share/doc/fzf/examples/completion.zsh
[ -f /usr/share/doc/fzf/examples/key-bindings.zsh ] && . /usr/share/doc/fzf/examples/key-bindings.zsh
[ -f $ZDOTDIR/completion/_fnm ] && fpath+="$ZDOTDIR/completion/"
# [ -f ~/.fzf.zsh ] && . ~/.fzf.zsh
compinit

# Edit line in vim with ctrl-e:
autoload edit-command-line; zle -N edit-command-line
bindkey '^e' edit-command-line

# ENABLE_CORRECTION="true"
setopt autocd

# Prompt for spelling correction of commands.
setopt CORRECT

# Customize the style that the suggestions are shown with.
# See https://github.com/zsh-users/zsh-autosuggestions/blob/master/README.md#suggestion-highlight-style
ZSH_AUTOSUGGEST_HIGHLIGHT_STYLE='fg=4,bold,underline"'

# Set what highlighters will be used.
# See https://github.com/zsh-users/zsh-syntax-highlighting/blob/master/docs/highlighters.md
ZSH_HIGHLIGHT_HIGHLIGHTERS=(main brackets)

# Customize the main highlighter styles.
# See https://github.com/zsh-users/zsh-syntax-highlighting/blob/master/docs/highlighters/main.md#how-to-tweak-it
typeset -A ZSH_HIGHLIGHT_STYLES
ZSH_HIGHLIGHT_STYLES[comment]='fg=14'
# Define default styles.
# ZSH_HIGHLIGHT_STYLES[default]=none
# ZSH_HIGHLIGHT_STYLES[unknown-token]=fg=red,bold
# ZSH_HIGHLIGHT_STYLES[reserved-word]=fg=yellow
# ZSH_HIGHLIGHT_STYLES[suffix-alias]=fg=green,underline
# ZSH_HIGHLIGHT_STYLES[global-alias]=fg=cyan
# ZSH_HIGHLIGHT_STYLES[precommand]=fg=green,underline
# ZSH_HIGHLIGHT_STYLES[commandseparator]=none
# ZSH_HIGHLIGHT_STYLES[autodirectory]=fg=green,underline
# ZSH_HIGHLIGHT_STYLES[path]='underline'
# ZSH_HIGHLIGHT_STYLES[path_pathseparator]=
# ZSH_HIGHLIGHT_STYLES[path_prefix_pathseparator]=
# ZSH_HIGHLIGHT_STYLES[globbing]=fg=blue
# ZSH_HIGHLIGHT_STYLES[history-expansion]=fg=blue
# ZSH_HIGHLIGHT_STYLES[command-substitution]=none
# ZSH_HIGHLIGHT_STYLES[command-substitution-delimiter]=fg=magenta
# ZSH_HIGHLIGHT_STYLES[process-substitution]=none
# ZSH_HIGHLIGHT_STYLES[process-substitution-delimiter]=fg=magenta
ZSH_HIGHLIGHT_STYLES[single-hyphen-option]='fg=cyan'
ZSH_HIGHLIGHT_STYLES[double-hyphen-option]='fg=cyan'
# ZSH_HIGHLIGHT_STYLES[back-quoted-argument]=none
# ZSH_HIGHLIGHT_STYLES[back-quoted-argument-delimiter]=fg=magenta
# ZSH_HIGHLIGHT_STYLES[single-quoted-argument]=fg=yellow
# ZSH_HIGHLIGHT_STYLES[double-quoted-argument]=fg=yellow
# ZSH_HIGHLIGHT_STYLES[dollar-quoted-argument]=fg=yellow
# ZSH_HIGHLIGHT_STYLES[rc-quote]=fg=cyan
# ZSH_HIGHLIGHT_STYLES[dollar-double-quoted-argument]=fg=cyan
# ZSH_HIGHLIGHT_STYLES[back-double-quoted-argument]=fg=cyan
# ZSH_HIGHLIGHT_STYLES[back-dollar-quoted-argument]=fg=cyan
# ZSH_HIGHLIGHT_STYLES[assign]=none
# ZSH_HIGHLIGHT_STYLES[redirection]=fg=yellow
# ZSH_HIGHLIGHT_STYLES[comment]=fg=black,bold
# ZSH_HIGHLIGHT_STYLES[named-fd]=none
# ZSH_HIGHLIGHT_STYLES[numeric-fd]=none
# ZSH_HIGHLIGHT_STYLES[arg0]=fg=green
# format our main prompt for hostname current folder, and permissions.

# typeset -F SECONDS
# echo $SECONDS
# zprof
