#!/bin/sh

alias \
    cbrs="nsh openvpn3 namespaced-openvpn --run 'doas namespaced-openvpn --namespace cbr --config /usr/openvpn/cbremote.ovpn'" \
    cbrt="s ip netns exec cbr sudo -u \$USER -i foot" \
    cbr="s ip netns exec cbr sudo -u \$USER -i" \
    pvt="doas ip netns exec pvt-net1 doas -u davide" \
    pvtf="doas ip netns exec pvt-net1 doas -u davide firefox" \
    trra="doas ip netns exec pvt-net1 doas -u davide transmission-remote -a" \
    trrd="doas ip netns exec pvt-net1 doas -u davide transmission-remote -F d -l" \
    trrl="doas ip netns exec pvt-net1 doas -u davide transmission-remote -l" \
    trru="doas ip netns exec pvt-net1 doas -u davide transmission-remote -F u -l" \
    trrr5="doas ip netns exec pvt-net1 doas -u davide transmission-remote -F r:5 -l" \
    trrr6="doas ip netns exec pvt-net1 doas -u davide transmission-remote -F r:6 -l" \
    trrr56="doas ip netns exec pvt-net1 doas -u davide transmission-remote -F r:5 -F ~r:6 -l"

trrr() {
    doas ip netns exec pvt-net1 doas -u davide transmission-remote -F "r:$1" -l
}

trrrn() {
    doas ip netns exec pvt-net1 doas -u davide transmission-remote -F "r:$1" -F "~r:$2" -l
}

trre() {
    doas ip netns exec pvt-net1 doas -u davide transmission-remote "$@"
}
